modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "cobbledresearch"
version = "${version}"
displayName = "CobbledResearch"
authors = "Jigokusaru"
description = '''
A creature collector Mod
'''
#logoFile = ""

[[dependencies.cobbledresearch]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbledresearch]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbledresearch]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "cobbledresearch.mixins.json"
